version: '2.4'

services:
  node_main:
    build:
      context: ./e2e_tests
      dockerfile: docker-parity
      args:
        chain_spec_path: ./node_config/main_chain_spec.json
    container_name: node_main
    ports:
      - 8544:8545
    networks:
      - net_node_main

  node_side:
    build:
      context: ./e2e_tests
      dockerfile: docker-parity
      args:
        chain_spec_path: ./node_config/side_chain_spec.json
    container_name: node_side
    ports:
      - 8545:8545
    networks:
      - net_node_side
    # command: >
    #   --logging account_bloom,basicauthority,chain,client,dapps,discovery,diskmap,enact,engine,estimate_gas,ethash,executive,ext,external_tx,externalities,fatdb,fetch,hypervisor,ipc,jdb,journaldb,les,les_provider,local_store,migration,miner,mode,on_demand,own_tx,poa,rcdb,shutdown,signer,snapshot,snapshot_io,snapshot_watcher,spec,state,stats,stratum,sync,txqueue,rpc=trace
    command: >
      --logging txqueue,rpc=trace

  bridge_request:
    env_file: ./e2e_tests/env_override
    restart: 'no'
  bridge_collected:
    env_file: ./e2e_tests/env_override
    restart: 'no'
  bridge_affirmation:
    env_file: ./e2e_tests/env_override
    restart: 'no'
  bridge_senderhome:
    env_file: ./e2e_tests/env_override
    restart: 'no'
  bridge_senderforeign:
    env_file: ./e2e_tests/env_override
    restart: 'no'
